plugins {
    id "com.android.application"
}

android {
    namespace "io.github.wyt2002.trace"
    compileSdk 36

    defaultConfig {
        applicationId "io.github.wyt2002.trace"
        minSdk 23
        targetSdk 34
        versionCode 8
        versionName "1.2.0"
    }

    buildTypes {
        debug {}
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
